!obj:pylearn2.train.Train {
    dataset: &train !obj:contestTransformerDataset.TransformerDataset {
        raw : !obj:contest_dataset.ContestDataset {
            which_set: 'train',
            start: 0,
            stop: 3500,
            preprocessor : !obj:pylearn2.datasets.preprocessing.Standardize {},
            fit_preprocessor: True,
            fit_test_preprocessor: True,
        },
        transformer : !obj:affineTransformer.ImageAffineTransformer {
            img_width : 48,
            img_height : 48,
            p_hsymetry : 0.5,
            p_translation : 1.0,
            min_translation_pixels : -2,
            max_translation_pixels : 2,
            p_rotation : 1.0,
            min_rotation_degrees : -2,
            max_rotation_degrees : 2,
            seed : 1234
        },
        space_preserving : True,
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 500,
                     sparse_init: 15,
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 7,
                     irange: 0.
                 }
                ],
        nvis: 2304,
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 100,
        line_search_mode: 'exhaustive',
        monitoring_dataset:
            {
                'train' : *train,
                'test'  : !obj:contest_dataset.ContestDataset {
                    which_set: 'train',
                    start: 3500,
                    stop: 4100,
                    preprocessor : !obj:pylearn2.datasets.preprocessing.Standardize {},            
                    fit_preprocessor: True,
                    fit_test_preprocessor: True,
                }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
            }, !obj:pylearn2.models.mlp.WeightDecay {
                coeffs: [ .00110, .00110 ]
            }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "test_y_misclass",
            prop_decrease: 0.,
            N: 30
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'test_y_misclass',
             save_path: "mlp_best.pkl"
        }
    ],
}
